<?php include(dirname(__DIR__)."/left-menu.phtml"); ?>
<?php $value_id = (new Xdelivery_Model_Xdelivery())->getCurrentValueId(); 
 $distance = (new Xdelivery_Model_Distance())
                        ->findAll(['value_id' => $value_id])->toArray();
?>
<div class="third-main-panel">
<div class="row">
    <div class="col-md-12">
        <div class="page-content-wrapper form-horizontal">
            <div class="content solo-page">
                <h3 class="title-editor border-blue text-center">
                    <?php echo p__("xdelivery","Manage shipping distance cost"); ?>
               </h3>
                <div id="customer_forms" class="first-row-feature content-color container-fluid">
                    <div id="customer_form_new">
                       <form id="distanceForm" action="<?php echo $this->getUrl('xdelivery/settings/save-shipping-distance'); ?>" method="post" class="form-horizontal">
                        <input type="hidden" name="value_id" value="<?php echo $value_id; ?>">
                        
                        <table id="dynamic-attributes-values"
                               class="table content-white-bkg sb-pager">
                            <thead>
                                <tr class="border-grey">
                                    <th style="width: 5%;"></th>
                                    <th data-dynatable-column="name"
                                        style="width: 25%;"><?php echo  p__("xdelivery", "From (KM)"); ?></th>
                                        <th data-dynatable-column="name"
                                        style="width: 25%;"><?php echo  p__("xdelivery", "UP To (KM)"); ?></th>
                                     <th data-dynatable-column="price"
                                        style="width: 25%;"><?php echo  p__("xdelivery", "Price"); ?></th>  
                                    <th style="width: 20%;"></th>
                                </tr>
                            </thead>
                               <tbody class="connectedSortable" id="TextBoxContainer">
                                <?php if(!empty($distance)): 
                                    foreach ($distance as $key => $value) {
                                    
                                ?>
                                    <tr class="dynarow" id="element_1">
                                       <td></td>
                                       <td> 
                                           <div class="form-group">
                                                <div class="col-sm-12">
                                                     <input type="hidden" value="<?php echo $value['id'] ?>" name="id[]" />
                                                    <input type="text" value="<?php echo $value['from_km'] ?>" class="required input-flat value_name name_element_1" name="from_distance[]" placeholder="Enter Nickname" />
                                                </div>
                                            </div>
                                        </td>
                                         <td> 
                                           <div class="form-group">
                                                <div class="col-sm-12">
                                                    <input type="text" value="<?php echo $value['upto_km'] ?>" class="required input-flat value_name name_element_1" name="upto_distance[]" placeholder="Enter Nickname" />
                                                </div>
                                            </div>
                                        </td>
                                         <td> 
                                           <div class="form-group">
                                                <div class="col-sm-12">
                                                    <input type="text" value="<?php echo $value['amount'] ?>" class="required input-flat value_price price_element_1" name="price[]"  placeholder="Enter a Price"  />
                                                </div>
                                            </div>
                                        </td>
                                        <td>
                                            <a  class="delete-distance btn btn-danger" href="/xdelivery/settings/delete-distance/id/<?php echo $value['id']; ?>"><i class="fa fa-remove"></i></a> 
                                        </td>
                                    </tr>
                                <?php }
                                 else: ?>

                                      <tr class="dynarow" id="element_1">
                                       <td></td>
                                       <td> 
                                           <div class="form-group">
                                                <div class="col-sm-12">
                                                     <input type="hidden" value="" name="id[]" />
                                                    <input type="text" value="" class="required input-flat value_name name_element_1" name="from_distance[]" placeholder="Enter Nickname" />
                                                </div>
                                            </div>
                                        </td>
                                         <td> 
                                           <div class="form-group">
                                                <div class="col-sm-12">
                                                    <input type="text" value="" class="required input-flat value_name name_element_1" name="upto_distance[]" placeholder="Enter Nickname" />
                                                </div>
                                            </div>
                                        </td>
                                         <td> 
                                           <div class="form-group">
                                                <div class="col-sm-12">
                                                    <input type="text" value="0" class="required input-flat value_price price_element_1" name="price[]"  placeholder="Enter a Price"  />
                                                </div>
                                            </div>
                                        </td>
                                        <td>
                                            <button type="button" data-id="element_1" class="btn btn-danger remove"><i class="fa fa-remove"></i></button>
                                        </td>
                                    </tr>

                                 <?php endif; ?>

                                </tbody>
                                <tfoot>
                                    <tr>
                                    <td></td>
                                    <td>
                                        <a class="add-attribute-value btn btn-info" id="btnAdd">
                                           <?php echo  p__("xdelivery", "Add "); ?>
                                        </a>
                                      </td>
                                      <td>
                                      </td>
                                    </tr>
                                </tfoot> 
                            </table>
                            <p>
                                <span class="drag_and_drop_warning_message" style="display: none;color: #dea435;" >
                                 <?php echo  p__("xdelivery", "Please note that you need to click the Save Changes button to commit the changes"); ?>
                             </span>
                            </p>
                            <div class="form-group">
                                <div class="col-md-12 col-sm-2 col-xs-12">
                                   <button id="sb-tour-save_user" type="submit" class="color-blue btn pull-right sb-tour"><?php echo p__("xdelivery", "Save"); ?></button>
                                </div>
                            </div>  
                        </form>                        
                     </div>
                </div> 
            </div>
        </div>
    </div>
  </div>
</div>

<script type="text/javascript">
    
$(function () {
    var totalRowCount = $("#TextBoxContainer tr").length;
    $("#btnAdd").bind("click", function () {
        totalRowCount = totalRowCount + 1;
        var div = $("<tr  class='dynarow' id='element_"+totalRowCount+"' />");
        div.html(GetDynamicTextBox(totalRowCount));
        $("#TextBoxContainer").append(div);
    
    });

    $("body").on("click", ".remove", function () {
        var removeValues = $(this).closest("tr").children('td').find(".name").val();
        /*Call ajax and remove from database*/
        $(this).closest("tr").remove();
    });

    function GetDynamicTextBox(totalRowCount) {       
        return '<td></td><td><div class="form-group"><div class="col-sm-12"> <input type="hidden" value="0" name="id[]" /><input type="text" value="" class="required input-flat value_name name_element_'+totalRowCount+'" name="from_distance[]" placeholder="From (KM)"  /></div></div>'+ '</td><td><div class="form-group"><div class="col-sm-12"><input type="text" value="" class="required input-flat value_name name_element_'+totalRowCount+'" name="upto_distance[]" placeholder="UP TO (KM)"  /></div></div>'+ '</td><td><div class="form-group"><div class="col-sm-12"><input type="text" value="0" class="required input-flat value_price price_element_'+totalRowCount+'" name="price[]" placeholder="Enter a Price" /></div></div>'+ '</td><td><button type="button" class="btn btn-danger remove" data-id="element_'+totalRowCount+'" ><i class="fa fa-remove"></i></button></td>'
    }
 
});

$('#distanceForm').submit(function() {
    if($(this).valid()) {
        reload(this, this.action, true, function(data) {
            if(data.success) {
               setTimeout(function () {
                        location.reload();
                    }, 300)
            }
        });
    }
    return false;
});

$(document).off("click", ".delete-distance");
    $(document).on("click", ".delete-distance", function (e) {
        e.preventDefault();
        let deleteHref = $(this).attr("href");
        swal({
            title: '<?php echo P__("xdelivery", "Confirmation") ?>',
            text: '<?php echo P__("xdelivery", "Are you sure you want to delete this distance values?") ?>',
            showCancelButton: true,
            confirmButtonColor: '#0099C7',
            confirmButtonText: '<?php echo P__("xdelivery", "Yes, delete!")?>',
            cancelButtonText: '<?php echo P__("xdelivery", "No, go back") ?>',
            buttons: true
        }, function(value) {
            if (!value) {
                return false;
            }

            formget(deleteHref,
                {},
                function (data) {
                    feature_form_success(data.message);
                   // Reload only on success and when done!
                    setTimeout(function () {
                        location.reload();
                    }, 300)
                },
                function (data) {
                    feature_form_error(JSON.parse(data.responseText).message);
                },
                false);
        });
    });

</script>

 