<?php include(dirname(__DIR__)."/left-menu.phtml"); ?>
<?php   $value_id = (new Xdelivery_Model_Xdelivery())->getCurrentValueId();
?>

<div class="third-main-panel">
<div class="row">
    <div class="col-md-12">
        <div class="page-content-wrapper form-horizontal">
            <div class="content solo-page">
                <h3 class="title-editor border-blue text-center">
                    <?php echo p__("xdelivery","Create a new Category"); ?>
               </h3>
                  <div id="customer_forms" class="first-row-feature content-color container-fluid">
                    <div id="customer_form_new">

                        <form id="couponForm" action="<?php echo $this->getUrl('xdelivery/coupons/save'); ?>" method="post" class="form-horizontal">
                              <input type="hidden" name="value_id" value="<?php echo $value_id ?>">
                             <div class="form-group">
                                <div class="col-md-6">

                                     <div class="form-group">
                                        <div class="col-sm-4">
                                            <label for="name"><?php echo p__("xdelivery", 'Title'); ?><span>*</span></label>
                                        </div>
                                        <div class="col-sm-8">
                                            <input type="text" value="" class="required input-flat" required name="name" id="name" />
                                        </div>
                                    </div>

                                   <div class="form-group">
                                        <div class="col-sm-4">
                                            <label for="description"><?php echo p__("xdelivery", 'Description'); ?><span>*</span></label>
                                        </div>
                                        <div class="col-sm-8">
                                             <textarea  rows="12" cols="200" value="" class="input-flat" name="description" required id="description"></textarea>
                                        </div>
                                    </div>

                                     <div class="form-group">
                                        <div class="col-sm-4">
                                            <label for="coupon_code"><?php echo p__("xdelivery", 'Coupon code'); ?><span>*</span></label>
                                        </div>
                                        <div class="col-sm-8">
                                            <input type="text" value="" class="required input-flat" name="coupon_code" id="coupon_code" required />
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <div class="col-sm-4">
                                            <label for="discount_type"><?php echo p__("xdelivery", 'Discount Type'); ?></label>
                                        </div>
                                        <div class="col-sm-8">
                                           <select class="styled-select color-blue" name="discount_type" id="discount_type" required> 
                                            <option value=""><?php echo p__("xdelivery", 'Discount Type'); ?></option>
                                            <option value="percent"><?php echo p__("xdelivery", 'Percentage'); ?></option>
                                            <option value="fixed"><?php echo p__("xdelivery", 'Fixed'); ?></option>
                                            </select>
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <div class="col-sm-4">
                                            <label for="discount_value"><?php echo p__("xdelivery", 'Discount value'); ?><span>*</span></label>
                                        </div>
                                        <div class="col-sm-8">
                                            <input type="text" value="" class="required input-flat" name="discount_value" id="discount_value" required />
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <div class="col-sm-4">
                                            <label for="min_spend"><?php echo p__("xdelivery", 'Minimum amount of order'); ?><span>*</span></label>
                                        </div>
                                        <div class="col-sm-8">
                                            <input type="number" value="" class="required input-flat" name="min_spend" id="min_spend" required />
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <div class="col-sm-4">
                                            <label for="max_spend"><?php echo p__("xdelivery", 'Maximum amount of order'); ?><span>*</span></label>
                                        </div>
                                        <div class="col-sm-8">
                                            <input type="number" value="" class="required input-flat" name="max_spend" id="max_spend" required />
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <div class="col-sm-4">
                                            <label for="usage_limit_per_coupon"><?php echo p__("xdelivery", 'Use Limit per coupon'); ?><span>*</span></label>
                                        </div>
                                        <div class="col-sm-8">
                                            <input type="number" value="" class="required input-flat" name="usage_limit_per_coupon" id="usage_limit_per_coupon" required />
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <div class="col-sm-4">
                                            <label for="usage_limit_per_customer"><?php echo p__("xdelivery", 'Use Limit per customer'); ?><span>*</span></label>
                                        </div>
                                        <div class="col-sm-8">
                                            <input type="number" value="" class="required input-flat" name="usage_limit_per_customer" id="usage_limit_per_customer" required />
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <div class="col-sm-4">
                                            <label for="start_date"><?php echo p__("xdelivery", 'Start Date'); ?><span>*</span></label>
                                        </div>
                                        <div class="col-sm-8">
                                            <input type="text" value="" class="required input-flat" name="start_date" id="start_date" autocomplete="off" required />
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <div class="col-sm-4">
                                            <label for="end_date"><?php echo p__("xdelivery", 'End Date'); ?><span>*</span></label>
                                        </div>
                                        <div class="col-sm-8">
                                            <input type="text" value="" class="required input-flat" name="end_date" id="end_date" autocomplete="off" required/>
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <div class="col-sm-4">
                                            <label for="start_time"><?php echo p__("xdelivery", 'Start Time'); ?><span>*</span></label>
                                        </div>
                                        <div class="col-sm-8">
                                            <input type="text" value="" class="required input-flat" name="start_time" id="start_time" autocomplete="off" required/>
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <div class="col-sm-4">
                                            <label for="end_time"><?php echo p__("xdelivery", 'End Time'); ?><span>*</span></label>
                                        </div>
                                        <div class="col-sm-8">
                                            <input type="text" value="" class="required input-flat" name="end_time" id="end_time" autocomplete="off" required />
                                        </div>
                                    </div>
 
                                    <div class="form-group">
                                        <div class="col-sm-12">
                                            <label for="status" class="checkbox-inline">
                                                <input type="checkbox" id="status" name="status" value="1" class="color-blue checkbox sb-tour" />
                                               <?php echo p__("xdelivery", 'Active'); ?>
                                            </label>
                                        </div>
                                    </div>                               

                               </div>
                            </div>
                            
                            <div class="form-group">
                                <div class="col-md-12">
                                    * <?php echo p__("xdelivery", 'Required fields'); ?>
                                </div>
                            </div>
                            
                            <div class="form-group">
                                <div class="col-md-12 col-sm-2 col-xs-12">
                                    <a href="/xdelivery/coupons/list" id="cancel_coupons" class="color-blue btn sb-tour"><?php  echo p__("xdelivery", "Cancel"); ?></a>
                                    <button id="sb-tour-save_user" type="submit" class="color-blue btn pull-right sb-tour"><?php echo p__("xdelivery", "Save"); ?></button>
                                </div>
                            </div>
                           
                        </form>
                    </div>
                </div> 
            </div>
        </div>
    </div>
</div>
</div>

<script type="text/javascript">
    $('#couponForm').submit(function() {
        if($(this).valid()) {
            reload(this, this.action, true, function(data) {
                if(data.success) {
                   window.location = $('#cancel_coupons').attr( "href" );
                }
            });
        }
        return false;
    });

     /*Date Pickers*/
        if($.datepicker.regional['<?php echo Core_Model_Language::getCurrentLanguageDatepicker(); ?>']) {
            $.datepicker.setDefaults($.datepicker.regional['<?php echo Core_Model_Language::getCurrentLanguageDatepicker(); ?>']);
        } else {
            $.datepicker.setDefaults($.datepicker.regional['en']);
        }
        $( "#start_date" ).datepicker({
            changeMonth: true,
            changeYear: true,
            numberOfMonths: 1,
            dateFormat: 'yy-mm-dd',
            onClose: function( selectedDate ) {
                $( "#end_date" ).datepicker( "option", "minDate", selectedDate );
            }
        });
        $( "#end_date" ).datepicker({
            changeMonth: true,
            changeYear: true,
            numberOfMonths: 1,
            dateFormat: 'yy-mm-dd',
            onClose: function( selectedDate ) {
                $( "#start_date" ).datepicker( "option", "maxDate", selectedDate );
            }
        });

         $( "#start_time" ).timepicker({});
         $( "#end_time" ).timepicker({}); 
</script>