<?php include(dirname(__DIR__)."/left-menu.phtml"); 
 $value_id = (new Xdelivery_Model_Xdelivery())->getCurrentValueId();
    $stores = (new Xdelivery_Model_Store())
                ->findByValueId($value_id);
    $status = (new Xdelivery_Model_Orders)->getStatus();?>
<div class="third-main-panel">
    <div class="row">
        <div class="col-md-12">
            <div class="page-content-wrapper form-horizontal">
                <div class="content solo-page">
                    <h3 class="title-editor border-blue text-center">
                        <?php echo  p__("xdelivery", "Orders"); ?>
                    </h3>

                    <div class="subcontent content-color container-fluid">
                        <div class="form-group">
                            <div class="col-md-12">
                                <div id="row_filter_metrics">
                                    <div class="col-md-2 col-sm-12 col-xs-12">
                                        <select class="input-flat sb-tour dt-search color-blue" name="status"
                                            id="status" data-dynatable-query="status">
                                            <option value=""><?php echo p__("xdelivery", 'Select Status'); ?></option>
                                            <?php foreach ($status as $key => $sts) { ?>
                                            <option value="<?php echo $key; ?>">
                                                <?php echo $sts; ?></option>
                                            <?php } ?>
                                        </select>
                                    </div>

                                    <div class="col-md-2 col-sm-12 col-xs-12">
                                        <select class="input-flat sb-tour dt-search color-blue" name="store_id"
                                            id="store_id" data-dynatable-query="store_id">
                                            <option value=""><?php echo p__("xdelivery", 'Select Store'); ?></option>
                                            <?php foreach ($stores as $key => $store) { ?>
                                            <option value="<?php echo $store->getStoreId(); ?>">
                                                <?php echo $store->getStoreName(); ?></option>
                                            <?php } ?>
                                        </select>
                                    </div>

                                    <div class="col-md-2 col-sm-12 col-xs-12">
                                        <select class="input-flat sb-tour dt-search color-blue" name="date_type"
                                            id="date_type" data-dynatable-query="date_type">
                                            <option value=""><?php echo p__("xdelivery", 'Select Date Type'); ?>
                                            </option>
                                            <option value="booking_slot">
                                                <?php echo p__("xdelivery", 'Booking Slot'); ?></option>
                                            <option value="booking_date"><?php echo p__("xdelivery", 'Booking Date'); ?>
                                            </option>
                                        </select>
                                        <p><?php echo p__("xdelivery", 'Select date type for date filter'); ?>.</p>
                                    </div>
                                    <div class="col-md-1 col-sm-6 col-xs-6">
                                        <label for="from"><?php echo  p__("xdelivery", "From"); ?></label>
                                    </div>
                                    <div class="col-md-2 col-sm-6 col-xs-6">
                                        <input type="text" id="from" name="from" class="input-flat sb-tour dt-search"
                                            autocomplete="off" data-dynatable-query="from" disabled="disabled">
                                    </div>
                                    <div class="col-md-1 col-sm-6 col-xs-6">
                                        <label for="to"><?php echo  p__("xdelivery", "To"); ?></label>
                                    </div>
                                    <div class="col-md-2 col-sm-6 col-xs-6">
                                        <input type="text" id="to" name="to" class="input-flat sb-tour dt-search"
                                            autocomplete="off" data-dynatable-query="to" disabled="disabled">
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-12">

                                <table id="dynamic-orders" class="table content-white-bkg sb-pager">
                                    <thead>
                                        <tr class="border-grey">
                                            <th data-dynatable-column="id" style="width: 15%;">
                                                <?php echo  p__("xdelivery", "Order Number"); ?></th>
                                            <th data-dynatable-column="customer_firstname" style="width: 20%;">
                                                <?php echo  p__("xdelivery", "Customer"); ?></th>
                                            <th style="width: 7%;"><?php echo  p__("xdelivery", "Purchased"); ?></th>
                                            <th data-dynatable-column="total_amount" style="width: 15%;">
                                                <?php echo  p__("xdelivery", "Total"); ?></th>
                                            <th data-dynatable-column="status" style="width: 15%;">
                                                <?php echo  p__("xdelivery", "Status"); ?></th>
                                            <th data-dynatable-column="delivery_date" style="width: 20%;">
                                                <?php echo  p__("xdelivery", "Delivery/Puckup Slot"); ?></th>
                                            <th data-dynatable-column="created_at" style="width: 20%;">
                                                <?php echo  p__("xdelivery", "Booking Date"); ?></th>
                                            <th style="width: 5%;"><?php echo  p__("xdelivery", "Store"); ?></th>
                                            <th><?php echo  p__("xdelivery", "Actions"); ?></th>

                                        </tr>
                                    </thead>
                                    <tbody></tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<link href="/app/sae/design/desktop/flat/js/dynatable/jquery.dynatable.css" media="screen" rel="stylesheet"
    type="text/css">
<script type="text/javascript" src="/app/sae/design/desktop/flat/js/dynatable/jquery.dynatable.js"></script>

<style type="text/css">
#dynamic-customers {
    margin-top: 15px;
}
</style>

<script type="text/javascript">
$('#date_type').on('change', function() {
    if ($(this).val() != '') {
        $('#from').prop('disabled', false);
        $('#to').prop('disabled', false);
    } else {
        $('#from').prop('disabled', true);
        $('#to').prop('disabled', true);
    }
});

var uriParams = {};
let rowTemplate = `
    <tr class="dynarow">
        <td><a href="/xdelivery/orders/details/id/(ORDERID)">#(ORDERNUMBER)</a></td>
        <td>(FIRSTNAME) (LASTNAME)</td>
        <td>(QTY)</td>
        <td>(TOTALAMOUNT)</td>
        <td>(STATUS)</td>
        <td>(SLOT)</td>
        <td>(DATE)</td>
        <td>(STORE)</td>
        <td>
            <a href="/xdelivery/orders/details/id/(ORDERID)">
                <i class="fa fa-eye" aria-hidden="true"></i></a>
            <a class="print-order" style="display:none;" href="/xdelivery/orders/print/id/(ORDERID)">
                <i class="fa fa-print" aria-hidden="true"></i>
            </a>
            (ISMANAGED)
        </td>
        
    </tr>`;

function rowWriter(rowIndex, record, columns, cellWriter) {
    var isManagedBadge = record.is_managed != 1 ? '<span class="badge new-order-badge">' +
        '<?php echo __jss("New") ?>' + '</span>' : '';
    return rowTemplate
        .replace(/\(ORDERNUMBER\)/g, record.order_number)
        .replace(/\(ORDERID\)/g, record.order_id)
        .replace(/\(ISMANAGED\)/g, isManagedBadge)
        .replace(/\(FIRSTNAME\)/g, record.firstname)
        .replace(/\(LASTNAME\)/g, record.lastname)
        .replace(/\(DATE\)/g, record.created_at)
        .replace(/\(QTY\)/g, record.total_qty)
        .replace(/\(TOTALAMOUNT\)/g, record.total_amount)
        .replace(/\(SLOT\)/g, record.delivery_slot)
        .replace(/\(STORE\)/g, record.store_name)
        .replace(/\(STATUS\)/g, record.order_status);
}
$.dynatableSetup({
    table: {
        defaultColumnIdStyle: 'noStyle'
    },
    features: {
        paginate: true,
        sort: true,
        pushState: true,
        search: true,
        recordCount: true,
        perPageSelect: false,
    },
});

let tableCustomers = $('#dynamic-orders');

tableCustomers.bind('dynatable:preinit', function(e, dynatable) {
    dynatable.utility.textTransform.noStyle = function(text) {
        return text;
    };
});

tableCustomers.bind('dynatable:init', function(e, dynatable) {
    dynatable.queries.functions['to'] = function(r, val) {
        return queryValue;
    };
    dynatable.queries.functions['from'] = function(r, val) {
        return queryValue;
    };
    dynatable.queries.functions['date_type'] = function(r, val) {
        return queryValue;
    };

});

tableCustomers.bind('dynatable:afterProcess', function(e, data) {
    uriParams = data.queries;
});


tableCustomers.bind('dynatable:push', function(e, dynatable) {
    uriParams = dynatable.queries;
});

// And on the table
tableCustomers.dynatable({
    dataset: {
        ajax: true,
        ajaxUrl: '/xdelivery/orders/find-all',
        ajaxOnLoad: true,
        records: [],
        perPageDefault: 25
    },
    inputs: {
        processingText: '<?php echo __jss("Loading ...") ?>',
        searchPlaceholder: '<?php echo __jss("Search order ...") ?>',
        recordCountText: '<?php echo __jss("Showing") ?> ',
        filteredFrom: ' (<?php echo __jss("filtered from #TOTAL# total records") ?>)',
        recordText: '<?php echo __jss("record") ?>',
        recordTextPlural: '<?php echo __jss("records") ?>',
        textOf: '<?php echo __jss("of") ?>',
        textTo: '<?php echo __jss("to") ?>',
        queries: $('.dt-search')
    },
    writers: {
        _rowWriter: rowWriter
    }
});

$(document).ready(function() {
    if ($.datepicker.regional['<?php echo Core_Model_Language::getCurrentLanguageDatepicker(); ?>']) {
        $.datepicker.setDefaults($.datepicker.regional[
            '<?php echo Core_Model_Language::getCurrentLanguageDatepicker(); ?>']);
    } else {
        $.datepicker.setDefaults($.datepicker.regional['en']);
    }
    $("#from").datepicker({
        changeMonth: true,
        changeYear: true,
        numberOfMonths: 1,
        dateFormat: 'yy-mm-dd',
        onClose: function(selectedDate) {
            $("#to").datepicker("option", "minDate", selectedDate);
        }
    });

    $("#to").datepicker({
        changeMonth: true,
        changeYear: true,
        numberOfMonths: 1,
        dateFormat: 'yy-mm-dd',
        onClose: function(selectedDate) {
            $("#from").datepicker("option", "maxDate", selectedDate);
        }
    });
});


$(document).off("click", ".print-order");
$(document).on("click", ".print-order", function(e) {
    e.preventDefault();
    let printHref = $(this).attr("href");
    swal({
        title: '<?php echo P__("xdelivery", "Confirmation") ?>',
        text: '<?php echo P__("xdelivery", "Are you sure you want to print this Order?") ?>',
        showCancelButton: true,
        confirmButtonColor: '#0099C7',
        confirmButtonText: '<?php echo P__("xdelivery", "Yes, print!")?>',
        cancelButtonText: '<?php echo P__("xdelivery", "No, go back") ?>',
        buttons: true
    }, function(value) {
        if (!value) {
            return false;
        }

        formget(printHref, {},
            function(data) {
                feature_form_success(data.message);
                // Reload only on success and when done!
                location.reload();
            },
            function(data) {
                feature_form_error(JSON.parse(data.responseText).message);
            },
            false);
    });
});
</script>

<style type="text/css">
.dynatable-record-count {
    bottom: 0px !important;
}

.text-blue {
    color: #0099c7;
}

.new-order-badge {
    background-color: red;
}
</style>