<?php include(dirname(__DIR__)."/left-menu.phtml"); ?>
<?php $value_id = (new Xdelivery_Model_Xdelivery())->getCurrentValueId();?>
<?php $attribute = $this->getCurrentAttribute();  ?>

<div class="third-main-panel">
<div class="row">
    <div class="col-md-12">
        <div class="page-content-wrapper form-horizontal">
            <div class="content solo-page">
                <h3 class="title-editor border-blue text-center">
                    <?php echo p__("xdelivery","Edit Attribute"); ?>
               </h3>
                  <div id="customer_forms" class="first-row-feature content-color container-fluid">
                    <div id="customer_form_new">

                        <form id="attributesForm" action="<?php echo $this->getUrl('xdelivery/attributes/save'); ?>" method="post" class="form-horizontal">
                            <input type="hidden" name="value_id" value="<?php echo $attribute->getValueId(); ?>">
                            <input type="hidden" name="id" value="<?php echo $attribute->getId(); ?>" class="required input-flat"/>
                             <div class="form-group">
                                <div class="col-md-6">

                                     <div class="form-group">
                                        <div class="col-sm-4">
                                            <label for="attribute_name"><?php echo p__("xdelivery", 'Name'); ?><span>*</span></label>
                                        </div>
                                        <div class="col-sm-8">
                                            <input type="text" value="<?php echo $attribute->getAttributeName(); ?>" class="required input-flat" name="attribute_name" id="attribute_name" />
                                        </div>
                                    </div>
  

                                    <div class="form-group">
                                        <div class="col-sm-12">
                                            <label for="is_active" class="checkbox-inline">
                                                <input type="checkbox" id="is_active" name="is_active" value="1" class="color-blue checkbox sb-tour"  <?php echo $attribute->getIsActive() == 1 ? "checked='checked'" : ""; ?> />
                                               <?php echo p__("xdelivery", 'Active'); ?>
                                            </label>
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <div class="col-sm-12">
                                            <label for="is_filterable" class="checkbox-inline">
                                                <input type="checkbox" id="is_filterable" name="is_filterable" value="1" class="color-blue checkbox sb-tour"  <?php echo $attribute->getIsFilterable() == 1 ? "checked='checked'" : ""; ?> />
                                               <?php echo p__("xdelivery", 'Filterable'); ?>
                                               <span> <?php echo p__("xdelivery", 'Use this attribute for filtering products'); ?></span>
                                            </label>
                                        </div>
                                    </div>

                               </div>
                            </div>
                            
                            <div class="form-group">
                                <div class="col-md-12">
                                    * <?php echo p__("xdelivery", 'Required fields'); ?>
                                </div>
                            </div>
                            
                            <div class="form-group">
                                <div class="col-md-12 col-sm-2 col-xs-12">
                                    <a href="/xdelivery/attributes/list" id="cancel_attributes" class="color-blue btn sb-tour"><?php  echo p__("xdelivery", "Cancel"); ?></a>
                                    
                                    <button id="sb-tour-save_user" type="submit" class="color-blue btn pull-right sb-tour"><?php echo p__("xdelivery", "Save"); ?></button>
                                </div>
                            </div>
                           
                        </form>
                    </div>
                </div> 
            </div>
        </div>
    </div>
</div>
</div>

 
 
<script type="text/javascript">
    $('#attributesForm').submit(function() {
        if($(this).valid()) {
            reload(this, this.action, true, function(data) {
                if(data.success) {
                    window.location = $('#cancel_attributes').attr( "href" );
                }
            });
        }
        return false;
    });
</script>