<?php 
include(dirname(__DIR__)."/left-menu.phtml"); 
$app_id = $this->getApplication()->getId();
$value_id = (new Xdelivery_Model_Xdelivery())->getCurrentValueId();
$stores = (new Xdelivery_Model_Store())->findAll(['value_id' => $value_id, 'is_active' => 1]);
?>
<script type="text/javascript" language="javascript"
    src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
<script type="text/javascript" language="javascript"
    src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/pdfmake.min.js"></script>
<script type="text/javascript" language="javascript"
    src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/vfs_fonts.js"></script>
<script type="text/javascript" language="javascript"
    src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.html5.min.js"></script>
<script type="text/javascript" language="javascript"
    src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.print.min.js"></script>
<div id="third-main-panel" style='padding-left:100px;'>
    <div id='pagecontainer'>
        <div class="application_analytics application content" id="content">
            <h3 class="title-editor border-blue text-center"><?php echo p__('xdelivery', 'Xdelivery Sale Reports') ?>
            </h3>
            <div class="container-fluid subcontent content-color">
                <!-- Navigation Bar START -->
                <?php include(dirname(__DIR__)."/stats-top-menu.phtml"); ?>
                <!-- Navigation Bar End -->
                <!-- Stat Filter Start -->
                <div class="row">
                    <div class="col-md-2" style="padding-bottom:3px;">
                        <select id="store_id" class="input-flat color-blue" name="store_dropdown">
                            <option value="0"><?php echo p__('xdelivery', 'All Stores') ?></option>
                            <?php foreach ($stores as $store): ?>
                            <option value="<?= $store['store_id'] ?>">
                                <?= $store['store_name'] ?>
                            </option>
                            <?php endforeach; ?>
                        </select>
                    </div>
                    <div class="col-md-2" style="padding-bottom:3px;">
                        <select onChange="filterType()" id="range_filter" class="input-flat color-blue" name="">
                            <option value="1"><?php echo p__('xdelivery', 'Today') ?></option>
                            <option value="2"><?php echo p__('xdelivery', 'Last 7 Days') ?></option>
                            <option value="3" selected><?php echo p__('xdelivery', 'Last 30 Days') ?></option>
                            <option value="4"><?php echo p__('xdelivery', 'Last 90 Days') ?></option>
                            <option style="font-weight:600" value="100"><?php echo p__('xdelivery', 'Date Range') ?>
                            </option>
                        </select>
                    </div>
                    <div class="col-md-5" id="custom_date_filter_container" style="display:none;">
                        <div id="row_filter_metrics" class="row sb-tour">
                            <div class="col-md-2 col-sm-6 col-xs-6">
                                <label for="from"><?php echo p__('xdelivery', 'From'); ?></label>
                            </div>
                            <div class="col-md-4 col-sm-6 col-xs-6">
                                <input type="text" id="from" name="from" class="input-flat sb-tour">
                            </div>
                            <div class="col-md-2 col-sm-6 col-xs-6">
                                <label for="to"><?php echo p__('xdelivery', 'To'); ?></label>
                            </div>
                            <div class="col-md-4 col-sm-6 col-xs-6">
                                <input type="text" id="to" name="to" class="input-flat sb-tour">
                            </div>
                        </div>
                    </div>
                    <div class="col-md-1">
                        <button data-html2canvas-ignore="true" class="btn color-blue" onclick="loadSalesStats()">
                            <i class="fa fa-filter"></i>
                        </button>
                    </div>
                    <div class='col-md-2'>
                        <button style='float:right;' data-html2canvas-ignore='true' class="btn color-blue"
                            onclick="printPdf()">
                            <i class="fa fa-download"></i>
                            <span style="display:none;" id="pdf_download_loader"><i
                                    class="fa fa-circle-o-notch fa-spin fa-fw"></i></span>
                        </button>
                    </div>
                </div>
                <!-- Stat Filter End -->
                <!-- TOTAL SALES START-->
                <div class="row first-row-feature" style="padding-top:0px;">
                    <!-- <h3 class="fs-titel stat-headings"></i> <?php echo p__('xdelivery', 'All Sales') ?><span class='filter-time-stamp'></span></h3>                                                         -->
                    <div class="row" style="padding-left:20px;padding-right:20px;padding-top:10px;padding-bottom:10px;">
                        <div class="col-md-4">
                            <div class="stat-calculate" style="">
                                <p><?php echo p__('xdelivery', 'Total Sales Count') ?></p>
                                <h1 class="dfault-0" id="total_sales_count"></h1>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="stat-calculate" style="">
                                <p><?php echo p__('xdelivery', 'Total Sales Revenue') ?></p>
                                <h1 class="dfault-0" id="total_sales_gross"></h1>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="stat-calculate" style="">
                                <p><?php echo p__('xdelivery', 'Total Discounts Applied') ?></p>
                                <h1 class="dfault-0" id="total_sales_discount"></h1>
                            </div>
                        </div>
                    </div>
                    <div class="row" style="padding-left:20px;padding-right:20px;padding-top:10px;padding-bottom:10px;">
                        <div class="col-md-4">
                            <div class="stat-calculate" style="">
                                <p><?php echo p__('xdelivery', 'Total Tax Collected') ?></p>
                                <h1 class="dfault-0" id="total_sales_tax"></h1>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="stat-calculate" style="">
                                <p><?php echo p__('xdelivery', 'Total Tips Received') ?></p>
                                <h1 class="dfault-0" id="total_sales_tip"></h1>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="stat-calculate" style="">
                                <p><?php echo p__('xdelivery', 'Total Delivery Charges') ?></p>
                                <h1 class="dfault-0" id="total_sales_delivery"></h1>
                            </div>
                        </div>
                    </div>
                    <div class="row" style="padding-left:20px;padding-right:20px;padding-top:10px;padding-bottom:10px;">
                        <div class="col-md-12 col-xs-12" style="max-height:348px">
                            <div style="margin-left:46%;position: absolute;top: 40%;" id="total_sales_loader"
                                class="loader_metrics"><i
                                    class="fa fa-circle-o-notch fa-spin fa-3x fa-fw"></i><br /><?php echo p__('xdelivery', 'Loading...'); ?>
                            </div>
                            <canvas style="border:1px solid #dedddd" id="total_sales" class="content-white-bkg sb-tour"
                                width="400" height="340"></canvas>
                        </div>
                    </div>
                </div>
                <!-- TOTAL SALES END-->

            </div>
        </div>
    </div>
</div>
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdf.js/2.6.347/pdf.min.js"
    integrity="sha512-Z8CqofpIcnJN80feS2uccz+pXWgZzeKxDsDNMD/dJ6997/LSRY+W4NmEt9acwR+Gt9OHN0kkI1CTianCwoqcjQ=="
    crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/1.5.3/jspdf.debug.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/html2canvas/1.4.1/html2canvas.min.js"
    integrity="sha512-BNaRQnYJYiPSqHHDb58B0yaPfCu+Wgds8Gp/gU33kqBtgNS4tSPHuGibyoeqMV/TJlSKda6FXzoEyYGjTe+vXA=="
    crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script>
// START Date Picker
var today = new Date(); // get current date
var oneYearAgo = new Date(); // create new date object
oneYearAgo.setFullYear(today.getFullYear() - 1); // set year to previous year
if ($.datepicker.regional['<?php echo Core_Model_Language::getCurrentLanguageDatepicker(); ?>']) {
    $.datepicker.setDefaults($.datepicker.regional[
        '<?php echo Core_Model_Language::getCurrentLanguageDatepicker(); ?>']);
} else {
    $.datepicker.setDefaults($.datepicker.regional['en']);
}

$("#from").datepicker({
    changeMonth: true,
    changeYear: true,
    numberOfMonths: 3,
    minDate: oneYearAgo,
    onClose: function(selectedDate) {
        $("#to").datepicker("option", "minDate", selectedDate);
    }
});

$("#to").datepicker({
    changeMonth: true,
    changeYear: true,
    numberOfMonths: 3,
    onClose: function(selectedDate) {
        $("#from").datepicker("option", "maxDate", selectedDate);
    }
});
$("#to").datepicker('setDate', new Date());
$("#from").datepicker('setDate', -30);

function computeDateRange() {
    var start_timestamp = parseInt($.datepicker.formatDate("@", $("#from").datepicker("getDate")) / 1000);
    var end_timestamp = parseInt($.datepicker.formatDate("@", $("#to").datepicker("getDate")) / 1000);
    //We go to 23:59
    end_timestamp = end_timestamp + (60 * 60 * 24) - 60;
    date_range = {
        "start": start_timestamp,
        "end": end_timestamp
    };
    return date_range;
}
var date_range_params = '';

function filterStats() {
    if ($("#from").val() && $("#to").val()) {
        date_range_params = computeDateRange();
        if (date_range_params.start <= date_range_params.end) {
            console.log("Called");
        } else {
            var page_message = new AlertMessage(
                "<?php echo p__('xdelivery',"Start date must be lower than end date."); ?>");
            page_message.addButton(true);
            page_message.setTimer(false);
            page_message.isError(true);
            page_message.show();
        }
    } else {
        var page_message = new AlertMessage(
            "<?php echo p__('xdelivery',"You have to chose a start and an end date."); ?>");
        page_message.addButton(true);
        page_message.setTimer(false);
        page_message.isError(true);
        page_message.show();
    }
}
// END Date Picker    
// Chart identifiers
var date_range_sales_ctx = $("#date_range_sales");
var total_sales_ctx = $("#total_sales");
// Bar Chart Configrations                       
var datasetMeta = [{
    label: '<?php echo p__('xdelivery',"Gross Sale Values Overview"); ?>',
    backgroundColor: "#0099C7",
    borderColor: "#0099C7",
    borderWidth: 1,
    hoverBackgroundColor: "#0099C7",
    hoverBorderColor: "#0099C7",
    data: []
}];
var lineChartConfig = {
    type: 'line',
    data: {
        labels: [],
        datasets: datasetMeta
    },
    options: {
        "responsive": true,
        maintainAspectRatio: false,
        scales: {
            y: {
                min: 0,
                ticks: {
                    precision: 0
                }
            }
        },
        plugins: {
            tooltip: {
                callbacks: {
                    title: function(context) {
                        if (context[0].datasetIndex === 1) {
                            return prev_total_sale_labels[context[0].dataIndex];
                        }
                    }
                }
            }
        }
    }
};
// END line Chart Configrations        
// Report Range Section
var prev_total_sale_labels = [];
var date_range_sales = new Chart(date_range_sales_ctx, lineChartConfig);
var total_sales = new Chart(total_sales_ctx, lineChartConfig);
// Empty No Graph
loadSalesStats();
var is_custome_date_filter = 0;

function filterType() {
    range_filter = $("#range_filter").val();
    if (range_filter == 100) {
        is_custome_date_filter = 1;
        $("#custom_date_filter_container").show();
    } else {
        is_custome_date_filter = 0;
        $("#custom_date_filter_container").hide();
    }
}

function loadSalesStats() {
    //Show loaders  
    $("#date_range_sales_loader").show();
    $("#total_sales_loader").show();
    range_filter = $("#range_filter").val();
    store_id = $("#store_id").val();
    filterStats();
    $(".dfault-0").text(0); //Reset stats to 0
    $.ajax({
        method: "POST",
        dataType: 'json',
        url: "/xdelivery/stats/salesstats",
        data: {
            app_id: '<?php echo $app_id; ?>',
            value_id: '<?php echo $value_id; ?>',
            range_filter: range_filter,
            store_id: store_id,
            date_range_params: date_range_params,
            is_custome_date_filter: is_custome_date_filter
        }
    }).done(function(data) {
        if (true) { // (Total Sales Line Chart)                                
            var total_sale_labels = [];
            var total_sale = [];
            var success_sale = [];
            $.each(data.total_graph_sales, function(ind, elem) {
                total_sale_labels.push(elem.labels);
                prev_total_sale_labels.push(elem.prev_labels);
                total_sale.push(elem.total_net_sales);
                success_sale.push(elem.prev_sale);
            });
            total_sales.data.datasets[0].data = total_sale;
            total_sales.data.labels = total_sale_labels;
            total_sales.update();
        }
        if (true) { // Total Sales Count Show           
            if (data.total_sales_count[0]) {
                var salesData = data.total_sales_count[0];
                if (salesData.total_count !== null) {
                    $("#total_sales_count").text(salesData.total_count);
                }
                if (salesData.total_gross !== null) {
                    $("#total_sales_gross").text(salesData.total_gross);
                }
                if (salesData.total_discount !== null) {
                    $("#total_sales_discount").text(salesData.total_discount);
                }
                if (salesData.total_tip !== null) {
                    $("#total_sales_tip").text(salesData.total_tip);
                }
                if (salesData.total_delivery !== null) {
                    $("#total_sales_delivery").text(salesData.total_delivery);
                }
                if (salesData.total_tax !== null) {
                    $("#total_sales_tax").text(salesData.total_tax);
                }
            }
            $("#total_sales_loader").hide();

            // Background Work for PDF PRINT
            const divElement = document.getElementById('pagecontainer');
            // Get the innerHTML of the div element
            const htmlContent = divElement.innerHTML;
            $("#newcontent").remove();
            // Create a new element to pass the same data
            newElement = document.createElement('div');
            newElement.setAttribute('id', 'newcontent');
            newElement.style.width = '1284px';
            newElement.style.marginLeft = '200px';
            newElement.style.position = "absolute";
            newElement.style.bottom = "100%";
            newElement.innerHTML = htmlContent;
            // Get the duplicated chart canvas and chart instance
            duplicateChartCanvas = newElement.querySelector('#total_sales');
            duplicateChart = new Chart(duplicateChartCanvas, {
                type: total_sales.config.type,
                data: total_sales.config.data,
                options: total_sales.config.options
            });
            duplicateChartCanvas.style.height = '348px';
            // Manage filter elements for print
            from_date = $("#from").val();
            to_date = $("#to").val();
            range_filter = $("#range_filter").val();
            myDropdown = newElement.querySelector('#range_filter');
            optionWithValue100 = myDropdown.querySelector(`option[value="${range_filter}"]`);
            optionWithValue100.selected = true;

            store_filter = $("#store_id").val();
            myDropdown = newElement.querySelector('#store_id');
            optionWithValue100 = myDropdown.querySelector(`option[value="${store_filter}"]`);
            optionWithValue100.selected = true;

            fromInput = newElement.querySelector('#from');
            fromInput.setAttribute('value', from_date);
            toInput = newElement.querySelector('#to');
            toInput.setAttribute('value', to_date);
            document.body.appendChild(newElement);
        }
    }).error(function() {
        console.log("Error");
    });
}
// PDF Print execution
function printPdf() {
    const doc = new jsPDF();
    html2canvas(newElement.querySelector("#content")).then((canvas) => {
        var imgData = canvas.toDataURL();
        var imgWidth = 210;
        var pageHeight = 295;
        var imgHeight = canvas.height * imgWidth / canvas.width;
        var heightLeft = imgHeight;
        var doc = new jsPDF('p', 'mm');
        var position = 3; // give some top padding to first page
        doc.addImage(imgData, 'JPEG', 0, position, imgWidth, imgHeight);
        heightLeft -= pageHeight;
        while (heightLeft >= 0) {
            position = heightLeft - imgHeight; // top padding for other pages        
            doc.addPage();
            doc.addImage(imgData, 'JPEG', 0, position, imgWidth, imgHeight);
            heightLeft -= pageHeight;
        }
        doc.save('XDelivery Sales.pdf');
    });
}
</script>
<style>
/* Stat CSS */
.stat-calculate {
    padding-top: 8px;
    padding-bottom: 8px;
    background: #f7f7f7;
    text-align: center;
    transition: transform .7s;
}

.stat-calculate h1 {
    font-weight: 700;
    margin-top: 18px;
    margin-bottom: 21px;
    line-height: 40px;

}

.stat-calculate p {
    font-weight: 700;
    font-size: large;
    line-height: 35px;
    overflow: hidden;
}

.stat-headings {
    color: white;
    background-color: #0099C7;
    padding: 9px;
    margin-top: 14px;
    margin-bottom: 14px;
    margin-left: 20px;
    margin-right: 20px;
}

.pagecontainer {
    padding-left: 100px;
}

#row_filter_metrics label {
    line-height: 29px
}
</style>