<?php include(dirname(__DIR__)."/left-menu.phtml"); ?>
<div class="third-main-panel">
<div class="row">
    <div class="col-md-12">
        <div class="page-content-wrapper form-horizontal">
            <div class="content solo-page">
                <h3 class="title-editor border-blue text-center">
                    <?php echo  p__("xdelivery", "Brands"); ?>
                </h3>
                
                <div class="subcontent content-color container-fluid">
                    <div class="form-group">
                     <div class="col-md-12">
                            <a href="/xdelivery/brand/add" id="add_brand" class="color-blue btn sb-tour pull-right">
                                <?php echo  p__("xdelivery", "Create a new Brand"); ?>                          
                            </a>
                            <table id="dynamic-brand"
                                   class="table content-white-bkg sb-pager">
                                <thead>
                                    <tr class="border-grey">
                                        <th style="width: 15%;"><?php echo  p__("xdelivery", "Thumbnail"); ?></th>
                                        <th data-dynatable-column="name"
                                            style="width: 40%;"><?php echo  p__("xdelivery", "Name"); ?></th>
                                        <th data-dynatable-column="is_active"
                                            style="width: 10%;"><?php echo  p__("xdelivery", "Status"); ?></th>                                        
                                        <th style="width: 5%"></th>
                                        <th style="width: 5%"></th>
                                    </tr>
                                </thead>
                                <tbody class="connectedSortable"></tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</div>

<link href="/app/sae/design/desktop/flat/js/dynatable/jquery.dynatable.css"
      media="screen"
      rel="stylesheet"
      type="text/css">
<script type="text/javascript"
        src="/app/sae/design/desktop/flat/js/dynatable/jquery.dynatable.js"></script>

<style type="text/css">
    #dynamic-brand {
        margin-top: 15px;
    }
</style>

<script type="text/javascript">
    var uriParams = {};
    let rowTemplate = `
    <tr class="dynarow" id="element_(ID)">
        <td><img src="/images/application/(IMAGE)" width="40px" height="40px"></td>
        <td>(NAME)</td>
        <td>(STATUS)</td>
        <td>
        <a class="edit-brand btn btn-xs btn-info" href="/xdelivery/brand/edit/id/(ID)">
            <?php echo  p__("xdelivery", "Edit"); ?>
          </a>
        </td>
        <td> 
          <a class="delete-brand btn btn-xs btn-danger" href="/xdelivery/brand/delete/id/(ID)">
             <?php echo  p__("xdelivery", "Delete"); ?>
          </a>
        </td>
       
    </tr>`;

    function rowWriter(rowIndex, record, columns, cellWriter) {
        return rowTemplate
            .replace(/\(ID\)/g, record.id)    
            .replace(/\(IMAGE\)/g, record.image)        
            .replace(/\(NAME\)/g, record.name)
            .replace(/\(STATUS\)/g, record.is_active);
    }
    $.dynatableSetup({
        table: {
            defaultColumnIdStyle: 'noStyle'
        },
        features: {
            paginate: true,
            sort: true,
            pushState: true,
            search: true,
            recordCount: true,
            perPageSelect: false,
        },
    });

    let tableCustomers = $('#dynamic-brand');

    tableCustomers.bind('dynatable:preinit', function(e, dynatable) {
        dynatable.utility.textTransform.noStyle = function(text) {
            return text;
        };
    });
 
    tableCustomers.bind('dynatable:afterProcess', function (e, data) {
        uriParams = data.queries;
    });
    
     tableCustomers.bind('dynatable:push', function(e, dynatable) {
          uriParams = dynatable.queries;   
    });

    // And on the table
    tableCustomers.dynatable({
        dataset: {
            ajax: true,
            ajaxUrl: '/xdelivery/brand/find-all',
            ajaxOnLoad: true,
            records: [],
            perPageDefault: 25
        },
        inputs: {
            processingText: '<?php echo __jss("Loading ...") ?>',
            searchPlaceholder: '<?php echo __jss("Search Brand ...") ?>',
            recordCountText: '<?php echo __jss("Showing") ?> ',
            filteredFrom: ' (<?php echo __jss("filtered from #TOTAL# total records") ?>)',
            recordText: '<?php echo __jss("record") ?>',
            recordTextPlural: '<?php echo __jss("records") ?>',
            textOf: '<?php echo __jss("of") ?>',
            textTo: '<?php echo __jss("to") ?>',
            queries: $('.dt-search')
        },
        writers: {
            _rowWriter: rowWriter
        }
    });

    $(document).off("click", ".delete-brand");
    $(document).on("click", ".delete-brand", function (e) {
        e.preventDefault();
        let deleteHref = $(this).attr("href");
        swal({
            title: "<?php echo P__("xdelivery", "Confirmation") ?>",
            text: "<?php echo P__("xdelivery", "Are you sure you want to delete this Brand?") ?>",
            showCancelButton: true,
            confirmButtonColor: '#0099C7',
            confirmButtonText: "<?php echo P__("xdelivery", "Yes, delete!")?>",
            cancelButtonText: "<?php echo P__("xdelivery", "No, go back") ?>",
            buttons: true
        }, function(value) {
            if (!value) {
                return false;
            }

            formget(deleteHref,
                {},
                function (data) {
                    feature_form_success(data.message);
                   // Reload only on success and when done!
                    setTimeout(function () {
                        location.reload();
                    }, 1500)
                },
                function (data) {
                    feature_form_error(JSON.parse(data.responseText).message);
                },
                false);
        });
    });

   var $tabs = $('#dynamic-brand');
    $(document).ready(function() {   
     $( "tbody.connectedSortable" )
        .sortable({
            connectWith: ".connectedSortable",
            appendTo: $tabs,
            helper:"clone",
            cursor: 'move',
            zIndex: 999990,
            stop: function (event, ui) {
                var data = $(this).sortable('toArray');  
                           
               $.ajax({
                    method: "POST",
                    url : "<?php echo $this->getUrl('xdelivery/brand/sortable'); ?>",
                    data : { data : data, parent_id : 0 }
                  }).done(function( msg ) {
                 });
          }
        })
        .disableSelection();
    });
 
 </script>

<style type="text/css">
    .dynatable-record-count{
        bottom: 0px !important;
    }
    .text-blue{
        color: #0099c7;
    }
</style>